<a href="https://colab.research.google.com/github/Aniket1492/PdfML/blob/main/MainDemoRecommendationModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

In [2]:
import numpy as np
import tensorflow as tf
# tf.enable_eager_excecution()
print(tf.__version__)


2.15.0


In [52]:
import pandas as pd
Customerdata = pd.read_excel('/content/unmerged_tmp.xlsx')
Productcategory = pd.read_excel('/content/Product_category.xlsx')


In [84]:
num_recommendations = 2

Member = list(Customerdata['member_id'])
Unique_Member = list(set(Member))

Productname = list(Customerdata['Product Name'])
Unique_Productname = list(set(Productname))

ProductCategory = list(Customerdata['Product Category'])
Unique_ProductCategory = list(set(ProductCategory))

Quantity = list(Customerdata['Total Quantity '])

num_mem = len(Unique_Member)
num_Product = len(Unique_Productname)
num_cat = len(Unique_ProductCategory)

print(len(Unique_Productname))
print(len(Unique_Member))

75
347


In [17]:
Customerdata["Total Quantity "]

0      3
1      1
2      1
3      2
4      1
      ..
911    1
912    1
913    1
914    1
915    1
Name: Total Quantity , Length: 916, dtype: int64

In [81]:
member_product = []
Quantity=0
for eachmember in Unique_Member:
    mem_list = []

    for eachproduct in Unique_Productname:
       Quantity=0
       for ind in Customerdata.index:
          if eachmember == Customerdata["member_id"][ind] and eachproduct == Customerdata["Product Name"][ind]:
            #print(eachmember)
            #print(eachproduct)
            Quantity = Customerdata["Total Quantity "][ind]
           # print(Quantity)

       mem_list.append(Quantity)
    member_product.append(mem_list)
tf. cast(member_product, tf. int32)
print(member_product)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [70]:
Product_Categoey = []
occur=0
for eachproduct in Unique_Productname:
      product_list = []

      for eachproductcat in Unique_ProductCategory:
        occur=0
        for ind in Productcategory.index:

            if eachproductcat == Productcategory["Product Category"][ind] and eachproduct == Productcategory["Product Name"][ind]:
              #print(eachmember)
              #print(eachproduct)
               occur = 1
            # print(Quantity)

        product_list.append(occur)
      Product_Categoey.append(product_list)
tf. cast(Product_Categoey, tf. float32)
print(Product_Categoey)


[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 

In [72]:
usercatergory = tf.matmul(member_product,Product_Categoey)
tf. cast(usercatergory, tf. float32)
usercatergory

<tf.Tensor: shape=(347, 14), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

In [61]:
usercatergory = usercatergory/tf.reduce_sum(usercatergory,axis =1 ,keepdims = True)
usercatergory

<tf.Tensor: shape=(347, 14), dtype=float64, numpy=
array([[0.  , 0.  , 0.  , ..., 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ]])>

In [65]:
top_user_cat =tf.nn.top_k(usercatergory,num_cat)[1]
top_user_cat

<tf.Tensor: shape=(347, 14), dtype=int32, numpy=
array([[ 4,  5,  7, ..., 10, 12, 13],
       [ 8,  6,  0, ..., 11, 12, 13],
       [ 8,  0,  1, ..., 11, 12, 13],
       ...,
       [ 7,  0,  1, ..., 11, 12, 13],
       [10,  0,  1, ..., 11, 12, 13],
       [10,  0,  1, ..., 11, 12, 13]], dtype=int32)>

In [67]:
for i in range(num_mem):
  cat_names = [Unique_ProductCategory[int(index)] for index in top_user_cat[i]]
  print('{}:{}'.format(Unique_Member[i],cat_names))

member-610e80d66d6209132503c53f:['Mooncake', 'Delivery', 'Promotion', 'Cake', 'Scone', 'Mini Cakes', 'Drink', 'Halloween', 'Cookie', 'Brownie', 'Topping', 'Bread and Croissant', 'Tart', 'Jam']
member-602e497f3521563e25d23abf:['Brownie', 'Cookie', 'Scone', 'Mini Cakes', 'Drink', 'Halloween', 'Mooncake', 'Delivery', 'Promotion', 'Topping', 'Bread and Croissant', 'Cake', 'Tart', 'Jam']
member-65a919dcf60e47f800c08597:['Brownie', 'Scone', 'Mini Cakes', 'Drink', 'Halloween', 'Mooncake', 'Delivery', 'Cookie', 'Promotion', 'Topping', 'Bread and Croissant', 'Cake', 'Tart', 'Jam']
member-656c34d1f60e47f800c05bb9:['Delivery', 'Cookie', 'Mooncake', 'Brownie', 'Scone', 'Mini Cakes', 'Drink', 'Halloween', 'Promotion', 'Topping', 'Bread and Croissant', 'Cake', 'Tart', 'Jam']
member-5ff947a2ae5f5148f31444ca:['Cookie', 'Delivery', 'Scone', 'Mini Cakes', 'Drink', 'Halloween', 'Mooncake', 'Promotion', 'Brownie', 'Topping', 'Bread and Croissant', 'Cake', 'Tart', 'Jam']
member-65b9ecc1f60e47f800c089f3:['D

In [79]:
users_Quantity = tf.matmul(usercatergory,tf.transpose(Product_Categoey))
tf. cast(users_Quantity, tf. int32)
users_Quantity

<tf.Tensor: shape=(347, 75), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 3, 0, ..., 0, 0, 0]], dtype=int32)>

In [83]:
user_Quantity_new = tf.where(tf.equal(member_product,tf.zeros_like(member_product)),
                           users_Quantity,
                           tf.zeros_like(tf.cast(member_product,tf.int32)))
user_Quantity_new

<tf.Tensor: shape=(347, 75), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 3, 0, ..., 0, 0, 0]], dtype=int32)>

In [85]:
top_product = tf.nn.top_k(user_Quantity_new,num_recommendations)[1]
top_product

<tf.Tensor: shape=(347, 2), dtype=int32, numpy=
array([[11, 12],
       [19, 68],
       [19, 53],
       [ 5, 15],
       [ 3,  5],
       [ 3,  5],
       [ 0,  2],
       [ 7,  8],
       [10, 14],
       [ 0, 36],
       [10, 11],
       [ 1,  7],
       [ 7,  8],
       [ 5, 15],
       [ 3,  5],
       [ 1,  7],
       [ 0, 36],
       [19,  3],
       [19, 53],
       [ 0, 36],
       [ 0,  2],
       [ 1,  6],
       [ 1,  8],
       [ 0,  1],
       [19, 68],
       [10, 14],
       [21, 23],
       [19, 68],
       [21, 23],
       [ 0,  2],
       [ 3,  5],
       [ 1,  7],
       [ 0, 36],
       [ 1,  7],
       [19, 53],
       [19, 53],
       [10, 31],
       [10, 14],
       [ 1,  7],
       [19, 53],
       [10, 11],
       [ 1,  7],
       [ 3,  5],
       [10,  3],
       [ 8, 10],
       [10, 14],
       [ 3,  5],
       [10, 11],
       [19, 53],
       [19, 68],
       [ 3,  5],
       [21, 23],
       [19, 68],
       [19, 68],
       [ 1,  8],
       [44,  1],


In [87]:
for i in range(num_mem):
  product_names = [Unique_Productname[int(index)] for index in top_product[i]]
  print('{}:{}'.format(Unique_Member[i],product_names))

member-610e80d66d6209132503c53f:['ไส้มะพร้าว', 'เปี๊ยะเจ 4 ชิ้น']
member-602e497f3521563e25d23abf:['Orange brownie ', 'Sea Salt Macadamia Toffee Browine / set']
member-65a919dcf60e47f800c08597:['Orange brownie ', 'Sea salt brownies (pcs.)']
member-656c34d1f60e47f800c05bb9:['Truffle Pop', 'Fruit Cake Cookies']
member-5ff947a2ae5f5148f31444ca:['Almond Dark Chocolate', 'Truffle Pop']
member-65b9ecc1f60e47f800c089f3:['Almond Dark Chocolate', 'Truffle Pop']
member-65b61184f60e47f800c088df:['Cranberry Rose Scones (L)', 'Original Scone']
member-65a7c1c0f60e47f800c08565:['Layer Bread ', 'Almond pretzel']
member-65a1038bf60e47f800c083dd:['เปี๊ยะส้ม', 'Wealthy box']
member-62d4cf1bf60e47f800bd2bb7:['Cranberry Rose Scones (L)', 'Cranberry Rose Scones (s)']
member-65acbb33f60e47f800c08647:['เปี๊ยะส้ม', 'ไส้มะพร้าว']
member-6517dfd9f60e47f800c03fbb:['Sourdough Pretzel Original', 'Layer Bread ']
member-659f8baff60e47f800c0834d:['Layer Bread ', 'Almond pretzel']
member-5f7fd191b1dfb87a7c96f8b7:['Truf